name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, huzaifa-jawad, shehroz ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Lint
        run: |
          flake8 .

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q || echo "No tests to run"

